// Comprehensive Directory of All 22 Official Languages Recognized by the
// Eighth Schedule of the Constitution of India + 1 Additional Language (English) = 23 Languages Total

export const CONSTITUTIONAL_LANGUAGES_COUNT = 22;

export const LANGUAGE_OPTIONS = [
  // 1. English (Common National & Administrative Language)
  {
    code: "en",
    label: "English",
    native: "English",
    english: "English",
    isConstitutional: false,
    region: "Pan-India / Global",
  },

  // 22 Official Languages of the 8th Schedule of the Constitution of India
  {
    code: "as",
    label: "অসমীয়া (Assamese)",
    native: "অসমীয়া",
    english: "Assamese",
    isConstitutional: true,
    region: "Assam",
  },
  {
    code: "bn",
    label: "বাংলা (Bengali)",
    native: "বাংলা",
    english: "Bengali",
    isConstitutional: true,
    region: "West Bengal, Tripura",
  },
  {
    code: "brx",
    label: "बड़ो (Bodo)",
    native: "बड़ो",
    english: "Bodo",
    isConstitutional: true,
    region: "Assam, Bodoland",
  },
  {
    code: "doi",
    label: "डोगरी (Dogri)",
    native: "डोगरी",
    english: "Dogri",
    isConstitutional: true,
    region: "Jammu and Kashmir",
  },
  {
    code: "gu",
    label: "ગુજરાતી (Gujarati)",
    native: "ગુજરાતી",
    english: "Gujarati",
    isConstitutional: true,
    region: "Gujarat, Daman & Diu",
  },
  {
    code: "hi",
    label: "हिन्दी (Hindi)",
    native: "हिन्दी",
    english: "Hindi",
    isConstitutional: true,
    region: "North & Central India",
  },
  {
    code: "kn",
    label: "ಕನ್ನಡ (Kannada)",
    native: "ಕನ್ನಡ",
    english: "Kannada",
    isConstitutional: true,
    region: "Karnataka",
  },
  {
    code: "ks",
    label: "कॉशुर / كٲشُر (Kashmiri)",
    native: "कॉशुर",
    english: "Kashmiri",
    isConstitutional: true,
    region: "Jammu and Kashmir",
  },
  {
    code: "gom",
    label: "कोंकणी (Konkani)",
    native: "कोंकणी",
    english: "Konkani",
    isConstitutional: true,
    region: "Goa, Maharashtra, Karnataka",
  },
  {
    code: "mai",
    label: "मैथिली (Maithili)",
    native: "मैथिली",
    english: "Maithili",
    isConstitutional: true,
    region: "Bihar, Jharkhand",
  },
  {
    code: "ml",
    label: "മലയാളം (Malayalam)",
    native: "മലയാളം",
    english: "Malayalam",
    isConstitutional: true,
    region: "Kerala, Lakshadweep",
  },
  {
    code: "mni",
    label: "মৈতৈলোন্ (Manipuri)",
    native: "মৈতৈলোন্",
    english: "Manipuri",
    isConstitutional: true,
    region: "Manipur",
  },
  {
    code: "mr",
    label: "मराठी (Marathi)",
    native: "मराठी",
    english: "Marathi",
    isConstitutional: true,
    region: "Maharashtra, Goa",
  },
  {
    code: "ne",
    label: "नेपाली (Nepali)",
    native: "नेपाली",
    english: "Nepali",
    isConstitutional: true,
    region: "Sikkim, West Bengal",
  },
  {
    code: "or",
    label: "ଓଡ଼ିଆ (Odia)",
    native: "ଓଡ଼ିଆ",
    english: "Odia",
    isConstitutional: true,
    region: "Odisha",
  },
  {
    code: "pa",
    label: "ਪੰਜਾਬੀ (Punjabi)",
    native: "ਪੰਜਾਬੀ",
    english: "Punjabi",
    isConstitutional: true,
    region: "Punjab, Delhi, Haryana",
  },
  {
    code: "sa",
    label: "संस्कृतम् (Sanskrit)",
    native: "संस्कृतम्",
    english: "Sanskrit",
    isConstitutional: true,
    region: "Classical / Pan-India",
  },
  {
    code: "sat",
    label: "ᱥᱟᱱᱛᱟᱲᱤ (Santali)",
    native: "ᱥᱟᱱᱛᱟᱲᱤ",
    english: "Santali",
    isConstitutional: true,
    region: "Jharkhand, Odisha, Bengal",
  },
  {
    code: "sd",
    label: "सिन्धी / سنڌي (Sindhi)",
    native: "सिन्धी",
    english: "Sindhi",
    isConstitutional: true,
    region: "Gujarat, Rajasthan, Maharashtra",
  },
  {
    code: "ta",
    label: "தமிழ் (Tamil)",
    native: "தமிழ்",
    english: "Tamil",
    isConstitutional: true,
    region: "Tamil Nadu, Puducherry",
  },
  {
    code: "te",
    label: "తెలుగు (Telugu)",
    native: "తెలుగు",
    english: "Telugu",
    isConstitutional: true,
    region: "Andhra Pradesh, Telangana",
  },
  {
    code: "ur",
    label: "اردو (Urdu)",
    native: "اردو",
    english: "Urdu",
    isConstitutional: true,
    region: "Jammu & Kashmir, UP, Telangana",
  },
];
